spring:
  server:
    port: 8080

  application:
    name: user-profile-post-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_profile_post
    username: postgres
    password: admin1234
    hikari:
      maximum-pool-size: 10

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    problemdetails:
      enabled: true


  flyway:
    enabled: false
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

security:
  jwt:
    secret-key: MY_SUPER_SECRET_KEY_123456789_123456789
    expiration: 86400000  # 24 hours

logging:
  pattern:
   # console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] user=%X{userId} %logger{36} - %msg%n" #%X{userId} = MDC value
  #              2026-02-06 14:22:10    [main]  user=10 ProfileService - Profile fetched



  level:
    root: INFO
    com.example.user_profile_post_api: DEBUG

